site_name: emakefun文档中心
site_url: https://emakefun.com
site_author: emakefun document team
site_description: 深圳易创空间科技有限公司产品资料文档中心
copyright: emakefun copyright 2017-2022
repo_name: Github
repo_url: https://github.com/emakefun/emakefun-doc

theme:
   name: 'readthedocs'
   language: 'zh'
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  feature:
    tabs: false

extra:
  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
nav:
    - 首页: index.md
    - MicroBit积木: micro_bit/micro_bit.md
    - Arduino可编程产品: arduino/arduino.md
    - 开源硬件: open_source_hardware/open_source_hardware.md
    - MagicBlock: magicblock/magicblock.md
    --关于我们: about.md