
site_name: emakefun文档中心
site_url: https://emakefun.com
site_author: emakefun document team
site_description: 深圳易创空间科技有限公司产品资料文档中心
copyright: emakefun copyright 2017-2022
repo_name: 'Github'
repo_url: https://github.com/emakefun/emakefun-docs

theme:
   name: 'mkdocs'
   custom_dir: 'custom_theme'
   language: 'cn'

   logo: 'url(images/favicon.jpg)'
   palette:
     primary: 'Teal'
     accent: 'Pink'

extra:
  search:
    language: 'jp'


nav:
    - 首页: index.md
    - 软件指导: 
      - 软件下载: softwareDownload.md
      # - 驱动安装:
    - 传感器/配件:
      - 总览: sensors/index.md
      - 基础输入模块:
        - 按键模块: sensors/base_modules/button_module.md
        - 触摸模块: sensors/base_modules/touch_module.md
        - 碰触开关: sensors/base_modules/collision_module.md
        - 旋转电位器: sensors/base_modules/rotary_potentiometer.md
        - 旋转编码器: sensors/base_modules/rotary_encoder_module.md
        - 触摸钢琴: sensors/base_modules/touch_piano.md
        - 滑动变阻器: sensors/base_modules/slide_potentiometer.md
        - 摇杆模块: sensors/base_modules/rocker_module.md
        - 触摸矩阵键盘: sensors/base_modules/matrix_keyboard_module.md
        - PH2.0小手柄: sensors/base_modules/joystick_handle.md
      - 传感器: 
        - 声音传感器: sensors/sensors/sound_sensor.md
        - 光敏传感器: sensors/sensors/photo_sensitive_sensor.md
        - 热敏传感器: sensors/sensors/thermal_sensor.md
        - 火焰传感器: sensors/sensors/flame_sensor.md
        - 土壤湿度传感器: sensors/sensors/soil_moisture_sensor.md
        - 雨滴传感器: sensors/sensors/water_droplets_sensor.md
        - 水深传感器: sensors/sensors/water_depth_sensor.md
        - 温湿度传感器: sensors/sensors/temperature_humidity_sensor.md
        - 温度DS18B20传感器: sensors/sensors/ds18b20_sensor.md
        - 气体传感器: sensors/sensors/mq_gas_sensor.md
        - 人体热释电传感器: sensors/sensors/human_body_sensor.md
        - 红外循迹模块传感器: sensors/sensors/tracking_sensor.md
        - 磁簧开关传感器: sensors/sensors/magnetic-switch_sensor.md
        - 灰度传感器: sensors/sensors/grayscale_sensor.md
        - 震动传感器: sensors/sensors/shock_sensor.md
        - 倾斜传感器: sensors/sensors/tilt_switch_sensor.md
        - 气压传感器: sensors/sensors/atmospheric_pressure_sensor.md
        - 压力传感器: sensors/sensors/pressure_sensor.md
        - 五路循迹传感器: sensors/sensors/five_way_tracking_sensor.md
        - 五路循迹传感器v2.0: sensors/sensors/five_way_tracking_sensor_v2.0.md
        # - 超声波传感器: sensors/sensors/ultrasonicSensor.md
        # - RGB超声波传感器: sensors/sensors/rgbUltrasonicSensor.md

      - 执行器: 
        - 有源蜂鸣器模块: sensors/actuators/buzzerModel.md
        - 无源蜂鸣器模块: sensors/actuators/passiveBuzzerModel.md
        - 直流电机模块: sensors/actuators/motorModel.md
        - 继电器模块: sensors/actuators/relayModel.md
        - 激光发射模块: sensors/actuators/laserEmissionModel.md
        - 振动马达: sensors/actuators/Vibration motor module.md
        - 大电机风扇模块: sensors/actuators/High power motor module.md
        # - 声音输出模块: sensors/actuators/Big Speaker Module.md
        # - 舵机模块: sensors/actuators/servoModel.md
        # - 双路电机驱动模块: sensors/actuators/highSpeedMiniMotorDriveBoardModel.md
        # - 普通红外遥控器模块: sensors/actuators/IRRemoteControlModel.md
        # - emakefun红外遥控器模块: sensors/actuators/emakefunIRRemoteControlModel.md
    
      - 显示器: 
        - LED灯: sensors/displayers/LED.md
        - 1602LCD显示屏: sensors/displayers/LCD1602.md
        - TM1650四位数码管: sensors/displayers/TM1650.md
        - TM1637四位时钟数码管: sensors/displayers/TM1637.md
        - 8x8点阵屏: sensors/displayers/8x8LedDisplay.md
        - 交通灯: sensors/displayers/trafficLights.md
        - RGB三色灯: sensors/displayers/RGB.md
        - WS2812B-RGB灯环: sensors/displayers/RGBRing.md
        - GT20L16S1Y OLED: sensors/displayers/GT20L16S1Y OLED.md
      - 通信模块:
        - 红外发射模块: sensors/actuators/infraredEmissionModel.md
        - 红外接收模块: sensors/actuators/irReceiverModel.md
      - 智能模块:
        - 颜色识别: sensors/smart_modules/color_recognition.md
        - 指南针传感器: sensors/smart_modules/compass.md
        - DS1302传感器: sensors/smart_modules/ds1302_rtc.md
        - MPU6050六轴陀螺仪: sensors/smart_modules/mpu6050.md
        - 手势传感器: sensors/smart_modules/gestureRecognitionSensor.md
        - LD3320语音识别模块: sensors/smart_modules/ld3320.md
        - MP3播放模块: sensors/smart_modules/MP3.md
        - MQTT物联网模块: sensors/smart_modules/esp8266_mqtt.md
        - 语音合成模块: sensors/smart_modules/tts_module.md
        - I2C扩展板模块: sensors/smart_modules/gpio_expansion_board.md
        
      - 电源模块:
        - 7.4V充电电池模块: sensors/power_module/2xcr123a_li_ion_battery_module.md
        - 3.7V升压充电模块: sensors/power_module/3.7V_Battery_Module.md
      
      
      #- 配件: micro_bit/IObit.md
    - Micro:bit产品:
      - Micro:bit主板介绍: micro_bit/microbit.md
      - Micro:bit编程介绍: micro_bit/microbit_code.md
      - IO:bit: micro_bit/IObit.md
      - Sensor:bit: micro_bit/sensorbit.md
      - Magic:bit: micro_bit/magicbit.md
      - Motor:bit: micro_bit/motorbit.md
      - Magic:bit四合一小车: micro_bit/FourInOneCar.md
      - Magic:bit麦轮小车: micro_bit/WheatwheelCar.md
      - Joysitck:Bit: micro_bit/joystickbit.md
    - Arduino产品: 
      - Arduino主板介绍: arduino/Hummerbot2.md
      - PH2.0传感器扩展板: arduino/SensorKit.md
      - Hummerbot: arduino/Hummerbot2.md
      # - Hummerbot图形化编程: arduino/Hummerbot.md
      - Happybot: arduino/Happybot.md
      - MirageTank: arduino/MirageTank.md
      - PantherTank: arduino/PantherTank.md
    - 树莓派: 
      - 树莓派传感器扩展板: RaspberryPi-Sensor-Board-master/README.md
      - 树莓派电机驱动板: RaspberryPi-MotorDriverBoard/README.md
    - ESP32产品:
      - ESP32: esp32/ESP32.md
    - 开源硬件: 
      - Ble-Nano: open_source_hardware/Ble-Nano.md
      - Ble-Uno: open_source_hardware/Ble-Uno.md
      - Maker-Uno: open_source_hardware/Maker-Uno.md
      - RF-Nano: open_source_hardware/RF-Nano.md
      - MotorDriverBoard: open_source_hardware/MotorDriverBoard.md
      - Rgb超声波(RUS-04): open_source_hardware/rgb.md
    - 软件: 
      - MagicBlock: open_source_software/magicblock.md
      - EmakefunApp: open_source_software/EmakefunApp.md
    - 关于我们: about.md
